case class Line(id:Long,
                authors:Array[Author],
                title:String,
                year:Int,
                n_citation:Int,
                page_start:String,
                page_end:String,
                doc_type:String,
                publisher:String,
                volume:String,
                issue:String,
                doi:String,
                references:Array[Long])//
